services:

  db:
    image: postgres:16-alpine
    container_name: loan_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data # Persist Data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql # Initialize the database with a script
      - ./db/sample_data.sql:/docker-entrypoint-initdb.d/sample_data.sql # Add sample data script in the same way
  
  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - db
    restart: always
    ports:
      - "${ADMINER_PORT}:${ADMINER_PORT}" # Exposed for database management (Development only)

volumes:
    db_data: