# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: risk.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'risk.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nrisk.proto\x12\x04risk\":\n\x0fLoanRiskRequest\x12\x0f\n\x07loan_id\x18\x01 \x01(\x05\x12\x16\n\x0e\x61\x63\x63ount_number\x18\x02 \x01(\t\"6\n\rLoanRiskReply\x12\x10\n\x08\x64\x65\x63ision\x18\x01 \x01(\t\x12\x13\n\x0brisk_status\x18\x02 \x01(\t2H\n\x0bRiskService\x12\x39\n\x0b\x41nalyzeRisk\x12\x15.risk.LoanRiskRequest\x1a\x13.risk.LoanRiskReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'risk_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOANRISKREQUEST']._serialized_start=20
  _globals['_LOANRISKREQUEST']._serialized_end=78
  _globals['_LOANRISKREPLY']._serialized_start=80
  _globals['_LOANRISKREPLY']._serialized_end=134
  _globals['_RISKSERVICE']._serialized_start=136
  _globals['_RISKSERVICE']._serialized_end=208
# @@protoc_insertion_point(module_scope)
