@startuml

skinparam classAttributeIconSize 0
skinparam class {
  BackgroundColor WhiteSmoke
  BorderColor DarkSlateGray
  ArrowColor DarkSlateGray
}

' Définition des entités avec couleurs spécifiques pour PK et FK
class Customer {
  + **id : Integer {PK}**
  full_name : String
  email : String
}

class Bank {
  + **id : Integer {PK}**
  name : String
  account_number_validity_pattern : String
  check_validity_pattern : String
}

class Account {
  + **account_number : String {PK}**
  <color:Blue>customer_id : Integer {FK}</color>
  <color:Blue>bank_id : Integer {FK}</color>
  balance : Float
}

class BankingTransaction {
  + **id : Integer {PK}**
  <color:Blue>account_number : String {FK}</color>
  transaction_type : String
  amount : Float
  transaction_date : Timestamp
}

class LoanApplication {
  + **id : Integer {PK}**
  <color:Blue>account_number : String {FK}</color>
  loan_amount : Decimal
  status : String
}

class Check {
  + **id : Integer {PK}**
  <color:Blue>account_number : Integer {FK}</color>
  check_number : String
  bank_id : String
  check_amount : Float
  status : String
}

class LoanMonitoring {
  + **id : Integer {PK}**
  <color:Blue>loan_application_id : Integer {FK}</color>
  monitoring_date : Timestamp
  risk_status : String
  check_validation_status : String
  loan_provider_status : String
  notification_status : String
  customer_status : String
}

' Relations explicites avec cardinalités
Customer "1" -- "0..n" Account
Bank "1" -- "0..n" Account
Account "1" -- "0..n" BankingTransaction
Account "1" -- "0..n" Check
Account "1" -- "0..n" LoanApplication
LoanApplication "1" -- "1" LoanMonitoring

@enduml