name: Lint (Python)

on:
  push:
    branches: [ staging, preprod, main ]
  pull_request:
    branches: [ staging, preprod, main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: |
            **/requirements*.txt
            **/pyproject.toml
            **/poetry.lock

      - name: Install lint tooling
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Run black (check only)
        run: |
          black --check .

      - name: Run isort (check only)
        run: |
          isort --check-only .

      - name: Run flake8
        run: |
          flake8 . --max-line-length=88 --extend-exclude .git,__pycache__,.venv,venv,dist,build
