name: Tests (Python + Postgres)

on:
  push:
    branches: [ staging, preprod, main ]
  pull_request:
    branches: [ staging, preprod, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        service: [ rest_service, graphql_service, grpc_service ]

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432/tcp
        options: >-
          --health-cmd="pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
          --health-interval=5s --health-timeout=5s --health-retries=10

    env:
      PGHOST: localhost
      PGPORT: ${{ job.services.postgres.ports['5432'] }}
      DATABASE_URL: postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@localhost:${{ job.services.postgres.ports['5432'] }}/${{ secrets.POSTGRES_DB }}
      SERVICE_DIR: ./${{ matrix.service }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: |
            ${{ env.SERVICE_DIR }}/requirements*.txt

      - name: Install psql client
        run: |
          sudo apt-get update -y
          sudo apt-get install -y postgresql-client

      - name: Install dependencies for ${{ matrix.service }}
        run: |
          python -m pip install --upgrade pip
          if ls "$SERVICE_DIR"/requirements*.txt >/dev/null 2>&1; then
            for req in "$SERVICE_DIR"/requirements*.txt; do
              echo "Installing $req"
              pip install -r "$req"
            done
          else
            echo "No requirements*.txt in $SERVICE_DIR"
          fi
          pip install pytest pytest-cov

      - name: Apply schema (db/init)
        env:
          PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: |
          DB="${{ secrets.POSTGRES_DB }}"
          if compgen -G "db/init/*.sql" > /dev/null; then
            for f in $(ls db/init/*.sql 2>/dev/null | sort); do
              echo "Applying schema: $f"
              psql -h "$PGHOST" -p "$PGPORT" -U "${{ secrets.POSTGRES_USER }}" \
                   -d "$DB" -v ON_ERROR_STOP=1 -f "$f"
            done
          else
            echo "No db/init SQL; skipping."
          fi

      - name: Seed CI data (db_ci_test/seed)
        env:
          PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          SEED_DIR: db_ci_test/seed
        run: |
          DB="${{ secrets.POSTGRES_DB }}"
          if compgen -G "$SEED_DIR/*.sql" > /dev/null; then
            for f in $(ls "$SEED_DIR"/*.sql 2>/dev/null | sort); do
              echo "Seeding: $f"
              psql -h "$PGHOST" -p "$PGPORT" -U "${{ secrets.POSTGRES_USER }}" \
                   -d "$DB" -v ON_ERROR_STOP=1 -f "$f"
            done
          else
            echo "No CI seeds in $SEED_DIR; skipping."
          fi

      - name: Run tests for ${{ matrix.service }}
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
        run: |
          CODE_DIR="$SERVICE_DIR/app"
          if [ -d "$CODE_DIR" ]; then
            pytest "$CODE_DIR" -q --maxfail=1 --disable-warnings \
              --cov="$CODE_DIR" --cov-report=xml:cov-${{ matrix.service }}.xml
          else
            echo "No $CODE_DIR; running service root if tests exist."
            if compgen -G "$SERVICE_DIR/tests/*.py" > /dev/null; then
              pytest "$SERVICE_DIR" -q --maxfail=1 --disable-warnings \
                --cov="$SERVICE_DIR" --cov-report=xml:cov-${{ matrix.service }}.xml
            else
              echo "No tests found for $SERVICE_DIR; skipping."
            fi
          fi

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.service }}
          path: cov-${{ matrix.service }}.xml
